version: '3'
services:
  app:
    build: .
    ports:
      - '5000:5000'
    restart: always
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/app
    depends_on:
      - app
    restart: always
