version: '3'
services:
  app:
    image: ghcr.io/qnx-emergingtech/galaan-fe:dev
    ports:
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - '8000:8000'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/app
    depends_on:
      - app
    restart: always
