version: '3.8'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always

  web:
    image: ghcr.io/qnx-emergingtech/galaan:dev
    command: python3 manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always


volumes:
  postgres_data:
