name: deploy-be-dev
on:
  registry_package:
    types: [published]
    package_name:
      - "galaan:dev"

  workflow_dispatch:

jobs:
  deploy-dev:
    name: Deploy Dev Backend
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: deploy_be_dev.yml
          directory: playbook
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          options: |
            --inventory inventory.yml
