name: stop-dev-fe
on:
  workflow_dispatch:

jobs:
  deploy-dev:
    name: Stop Dev Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: stop_fe_dev.yml
          directory: playbook
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          options: |
            --inventory inventory.yml
